name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [17] # Ensures compatibility with any Java 17 distribution
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17 (${{ matrix.java }}) (Any JDK)
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin' # Uses Eclipse Temurin JDK (compatible with all JavaFX libraries)

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Run tests
        run: ./gradlew test

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Caviar-JAR
          path: build/libs/Caviar.jar
